name: Guojin Chen @ CUHK-CSE
title: Guojin Chen @ CUHK-CSE
url: https://gjchen.me
description: Home page of Guojin Chen @ CUHK-CSE. He is now PhD student at The Chinese University of Hong Kong (CUHK-CSE) and his research interests include deep learning in VLSI, reinforcement learning and computer vision. He is advised by Prof. Bei Yu.
destination: ./_site
twitter: joyg_phd
lsi: false
port: 4000
markdown: kramdown
future: true
kramdown:
  parse_block_html: true
  syntax_highlighter: rouge
permalink: pretty
#seo
tagline: Home site for Guojin Chen @ CUHK-CSE | PhD | VLSI | Machine Learning | Guojin Chen | Guojin | CUHK | CSE | CS
#paginate: 5
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - .travis.yml
  - validate.rb
  - README.md
  - Gemfile
  - Gemfile.lock
  - bower_components
  - update-vendor-deps.sh
  - vendor/bundle
  - vendor/bower.json
